name: stadium_project
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Design
  cupertino_icons: ^1.0.6
  l: ^4.0.2

  # State management
  flutter_riverpod: ^2.5.1

  # Storage
  shared_preferences: ^2.3.2
  flutter_screenutil: ^5.9.3
  device_preview: ^1.2.0
  go_router: ^14.2.3
  flutter_svg: ^2.0.10+1

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter_gen:
  output: lib/gen/

  integrations:
    flutter_svg: true


flutter:
  uses-material-design: true

  assets:
    - assets/icons/ 
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
