name: stadium_project
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Design
  cupertino_icons: ^1.0.6
  l: ^4.0.2

  # State management
  flutter_riverpod: ^2.5.1

  # Storage
  shared_preferences: ^2.3.2


  flutter_screenutil: ^5.9.3
  device_preview: ^1.2.0
  go_router: ^14.2.7
  flutter_svg: ^2.0.10+1

  # Data fetching
  retrofit: ^4.2.0
  logger: ^2.4.0
  dio: ^5.6.0
  json_annotation: ^4.8.1

  # Ochiriladi
  http: ^1.2.2
  http_parser: ^4.0.2

  # Shimmer
  shimmer: ^3.0.0

  # Map
  maplibre_gl: ^0.20.0
  permission_handler: ^11.3.1
  geolocator: ^13.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  retrofit_generator: ^8.2.0
  json_serializable: ^6.6.2
  flutter_lints: ^4.0.0


flutter_gen:
  output: lib/gen/

  integrations:
    flutter_svg: true


flutter:
  uses-material-design: true

  assets:
    - assets/icons/ 
    - assets/images/ 
  
  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy/Gilroy-Black.ttf
          weight: 900
        - asset: assets/fonts/gilroy/Gilroy-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/gilroy/Gilroy-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Bold.ttf
          weight: 700
        - asset: assets/fonts/gilroy/Gilroy-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Heavy.ttf
          weight: 600
        - asset: assets/fonts/gilroy/Gilroy-HeavyItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/gilroy/Gilroy-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Medium.ttf
          weight: 500
        - asset: assets/fonts/gilroy/Gilroy-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Regular.ttf
          weight: 400
        - asset: assets/fonts/gilroy/Gilroy-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Light.ttf
          weight: 300
        - asset: assets/fonts/gilroy/Gilroy-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-Thin.ttf
          weight: 200
        - asset: assets/fonts/gilroy/Gilroy-ThinItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/gilroy/Gilroy-UltraLight.ttf
          weight: 100
        - asset: assets/fonts/gilroy/Gilroy-UltraLightItalic.ttf
          weight: 100
          style: italic
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
